#!/bin/sh
set -e

if [ ! -d "bundle/Vundle.vim" ]; then
  echo "Installing Vundle (https://github.com/gmarik/Vundle.vim)."
  git clone git@github.com:gmarik/Vundle.vim.git bundle/Vundle.vim
fi

vim +PluginInstall +qall
